#! /bin/sh

case "$1" in
  start)
    echo "Starting aesdsocket"
    start-stop-daemon -S -b -n aesdsocket -a /usr/bin/aesdsocket
    ;;
  stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K -n aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop}"
  exit 1
esac

exit 0

#Reference: Lecture on Canvas:https://www.coursera.org/learn/linux-system-programming-introduction-to-buildroot/lecture/EJdLo/linux-system-initialization
